# server {
#     listen      443 ssl;
#     server_name achanek.42.fr;

#     # SSL certificate (self-signed, generated in Dockerfile)
#     ssl_certificate     /etc/ssl/certs/nginx.crt;
#     ssl_certificate_key /etc/ssl/private/nginx.key;

#     # Only TLS 1.2 and 1.3 allowed (required by subject)
#     ssl_protocols TLSv1.2 TLSv1.3;

#     # WordPress files (shared volume with wordpress container)
#     root  /var/www/html;
#     index index.php index.html;

#     # Try the file, then directory, then fall back to WordPress index.php
#     location / {
#         try_files $uri $uri/ /index.php?$args;
#     }

#     # Pass ALL .php requests to WordPress/PHP-FPM via FastCGI
#     location ~ \.php$ {
#         # 'wordpress' is the Docker service name — Docker DNS resolves it
#         fastcgi_pass  wordpress:9000;
#         fastcgi_index index.php;
#         include       fastcgi_params;
#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#         fastcgi_param PATH_INFO $fastcgi_path_info;
#     }

#     # Block access to hidden files like .htaccess
#     location ~ /\. {
#         deny all;
#     }
# }

server {
    listen      443 ssl;
    server_name achanek.42.fr;

    ssl_certificate     /etc/ssl/certs/nginx.crt;
    ssl_certificate_key /etc/ssl/private/nginx.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    root  /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass  wordpress:9000;
        fastcgi_index index.php;
        include       fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO       $fastcgi_path_info;
        fastcgi_read_timeout          300;
    }

    location ~ /\. {
        deny all;
    }
}