[server]
http_port = 3000
domain = achanek.42.fr

# This is the key fix — tell Grafana it lives under /grafana/
root_url = https://achanek.42.fr/grafana/
serve_from_sub_path = true

[security]
admin_user = admin
admin_password = grafanapass123

[auth.anonymous]
enabled = false

[paths]
data = /var/lib/grafana
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins